# **NUMPY**

In [2]:
import numpy as np
a=np.array([1,2,3,4])            #1D Array
a

array([1, 2, 3, 4])

In [3]:
np.array([[1,2],[3,40]])            #2D array

array([[ 1,  2],
       [ 3, 40]])

In [4]:
np.array([1,2,3],"complex")

array([1.+0.j, 2.+0.j, 3.+0.j])

In [5]:
np.array((1,2,3))    #using tuple

array([1, 2, 3])