In [2]:
import numpy as np
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
a[[1,4,1,4,1,4,1]]

array([2, 5, 2, 5, 2, 5, 2])

In [3]:
index=np.array([1,4,5])
a[index]

array([2, 5, 6])

In [4]:
a[[1,4,5]]

array([2, 5, 6])

In [5]:
b=np.array([[1,2,3],[4,5,6],[3,2,4],[9,8,7]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 4],
       [9, 8, 7]])

In [6]:
b[[0,2],[2,0]]

array([3, 3])

In [7]:
b[[1,1,2],[0,2,1]]

array([4, 6, 2])

In [9]:
c=np.array([[1,-2,3],[4,-6,1]])
c

array([[ 1, -2,  3],
       [ 4, -6,  1]])

In [10]:
c[c<0]

array([-2, -6])

In [11]:
c[c<0]*2

array([ -4, -12])