# **Arange function**

## Arange( ) : 
Creates array of evenly spaced values

In [6]:
import numpy as np
np.arange(1,10)


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(3.0)

array([0., 1., 2.])

In [9]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [10]:
np.arange(20,dtype="complex")

array([ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
        7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
       14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j, 18.+0.j, 19.+0.j])

In [11]:
np.arange(1,10,2,dtype="float")

array([1., 3., 5., 7., 9.])