In [2]:
import numpy as np
a=np.arange(1,5)
a

array([1, 2, 3, 4])

In [4]:
a*3

array([ 3,  6,  9, 12])

In [3]:
a+2


array([3, 4, 5, 6])

In [5]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [6]:
a-1

array([0, 1, 2, 3])

In [7]:
a**2

array([ 1,  4,  9, 16])

In [9]:
b=np.array([10,20,30,40])
b

array([10, 20, 30, 40])

In [10]:
a

array([1, 2, 3, 4])

In [11]:
a+b

array([11, 22, 33, 44])

In [12]:
a*b

array([ 10,  40,  90, 160])