In [1]:
import numpy as np
a=np.zeros(5)
a.dtype

dtype('float64')

In [3]:
b=np.zeros(6,dtype=np.int8)
b

array([0, 0, 0, 0, 0, 0], dtype=int8)

In [4]:
x=np.float32(1)
x

1.0

In [6]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [7]:
a.astype(int)

array([0, 0, 0])

In [5]:
x.dtype

dtype('float32')