In [1]:
import numpy as np
b=np.array([[[1,2,3],[4,3,2],[5,4,3],[9,8,7]]])
b

array([[[1, 2, 3],
        [4, 3, 2],
        [5, 4, 3],
        [9, 8, 7]]])

In [2]:
b.flatten()

array([1, 2, 3, 4, 3, 2, 5, 4, 3, 9, 8, 7])

In [3]:
b.flatten(order="F")

array([1, 4, 5, 9, 2, 3, 4, 8, 3, 2, 3, 7])

In [4]:
b.flatten(order="K")

array([1, 2, 3, 4, 3, 2, 5, 4, 3, 9, 8, 7])

In [5]:
np.ravel(b)

array([1, 2, 3, 4, 3, 2, 5, 4, 3, 9, 8, 7])