# **1-D Array**

In [1]:
import numpy as np
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [2]:
a[3]

4

In [3]:
a[-2]

4

In [4]:
a[0]

1

# **2-D Array**

In [5]:
b=np.array([[1,2],[3,4]])
b

array([[1, 2],
       [3, 4]])

In [6]:
b[0][0]

1

In [8]:
b[1]

array([3, 4])

# **3-D Array**

In [10]:
c=np.array([[1,2,3,4],[4,5,6,3],[3,4,3,2],[2,4,5,6],[7,6,5,4],[9,8,0,77]])
c

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  3],
       [ 3,  4,  3,  2],
       [ 2,  4,  5,  6],
       [ 7,  6,  5,  4],
       [ 9,  8,  0, 77]])

In [12]:
d=np.array(c)
d

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  3],
       [ 3,  4,  3,  2],
       [ 2,  4,  5,  6],
       [ 7,  6,  5,  4],
       [ 9,  8,  0, 77]])

In [16]:
d[0][1]

2