# **Linspace**

In [2]:
import numpy as np
np.linspace(1,100,num=5, dtype="int")


array([  1,  25,  50,  75, 100])

In [3]:
np.linspace(1,100,num=5,endpoint=False,dtype="int")     #exclude 100

array([ 1, 20, 40, 60, 80])

In [4]:
#to check difference
np.linspace(1,100,num=4,retstep=True,dtype="int")

(array([  1,  34,  67, 100]), 33.0)

In [5]:
np.linspace(1,100,num=4,dtype=int)

array([  1,  34,  67, 100])

In [6]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])