**Importing Numpy Library**

In [1]:
import numpy as np

**Checking Version**

In [ ]:
print(np.__version__)
np.show_config()

**Create null vector of size 10**

In [3]:
Z=np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**Create null vector of size 10 but the fifth value is 1**

In [5]:
Z=np.zeros(10)
Z[4]=1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**Create a vector with values ranging from 10 to 49**

In [6]:
Z=np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


**Reversing the vector**

In [8]:
Z=np.arange(50)
Z=Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


**Creating 3x3 Matrix with values 0 to 8**

In [9]:
Z=np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Find the indices of non-zero elements from[1,2,0,0,4,0]**

In [10]:
nz=np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


**Create identity matrix**

In [11]:
Z=np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Create 3x3x3 array of random values**

In [12]:
Z=np.random.random((3,3,3))
print(Z)

[[[0.38997498 0.78243575 0.8563581 ]
  [0.36450452 0.43438269 0.78632206]
  [0.40436262 0.06515477 0.70825172]]

 [[0.10929489 0.05396542 0.51739409]
  [0.24487134 0.20173486 0.25967918]
  [0.7380511  0.13430044 0.62898235]]

 [[0.41897127 0.11427614 0.72271998]
  [0.41350848 0.79874585 0.84085202]
  [0.55483714 0.89134026 0.42243095]]]


**Create 10x10 array with random values and find the minimum and maximum values**

In [18]:
Z=np.random.random((10,10))
Zmin,Zmax=Z.min(),Z.max()
print(Z)
print('Values are:')
print('Zmin',Zmax)


[[0.10312945 0.25825743 0.98713614 0.08269577 0.60105278 0.87503968
  0.126098   0.2898472  0.11888076 0.23745718]
 [0.71675215 0.34855061 0.93567259 0.63782645 0.00788246 0.55974468
  0.09246018 0.64773569 0.16536009 0.64380653]
 [0.70327009 0.0997284  0.79101748 0.3083255  0.01985579 0.21204014
  0.80103497 0.16838652 0.06173259 0.47003912]
 [0.29773915 0.10985967 0.47617638 0.82600977 0.59729819 0.05995537
  0.22299783 0.2278669  0.59774603 0.55417201]
 [0.60307753 0.22475819 0.51232068 0.94726118 0.31379616 0.39500971
  0.01511142 0.57219947 0.02605685 0.14769684]
 [0.26874795 0.89034926 0.72691923 0.9721795  0.99673128 0.09403932
  0.92126187 0.46455972 0.11030739 0.71528792]
 [0.58670943 0.17162377 0.93422151 0.04774748 0.36640696 0.32438807
  0.24030795 0.6246225  0.84202757 0.00475308]
 [0.11381835 0.23782841 0.17090531 0.94993132 0.56815366 0.41037746
  0.61855022 0.23358304 0.67200011 0.58346925]
 [0.88375511 0.2571712  0.08055402 0.13618232 0.49152914 0.12510964
  0.26809039

** Creating random vector of size 30 and finding mean value**

In [19]:
Z=np.random.random(30)
m=Z.mean()
print(m)

0.5061394208500781


**Create 2d array witj 1 on the border and 0 inside**

In [21]:
Z=np.ones((10,10))
Z[1:-1,1:-1]=0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**Create 5x5 matrix with values 1,2,3,4 just below diagonal**

In [23]:
Z=np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


**Creating 8x8 matrix and fill it with a checkerboard pattern**









In [24]:
Z=np.zeros((8,8),dtype=int)
Z[1::2,::2]=1
Z[::2,1::2]=1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Creating 8x8 matrix using tile function**

In [25]:
Z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Create a custom dtype that describes a color as 4 unsigned bytes**

In [28]:
color=np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                ("b",np.ubyte,1),
                ("a",np.ubyte,1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


**Multiply 5x3 matrix bya 3x2 matrix** 

In [29]:
Z=np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


**Create 5x5 matrix with row values ranging from 0 to 4**

In [30]:
Z=np.zeros((5,5))
Z+=np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


**Consider a generator function that generates 10 integers and use it to build an array**

In [34]:
def generate():
  for x in range(10):
    yield x
Z=np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# **Sorting**

In [35]:
Z=np.random.random(10)
Z.sort()
print(Z)

[0.08922175 0.15537471 0.19532618 0.19868836 0.21883724 0.55565727
 0.70582989 0.70616208 0.80214671 0.86395799]
