# **Random Module**


*   rand()
*   randn()
*   ranf()
*   randint()



In [1]:
import numpy as np
np.random.rand(5)

array([0.49291264, 0.44272753, 0.529778  , 0.73136789, 0.97298904])

In [2]:
np.random.rand(4,5)

array([[0.69376184, 0.48970574, 0.87630572, 0.23495456, 0.87728599],
       [0.37179359, 0.458141  , 0.32899673, 0.71729994, 0.95563712],
       [0.37419135, 0.92242774, 0.01048153, 0.32473545, 0.23590327],
       [0.00298679, 0.89090902, 0.82588715, 0.65010184, 0.87665116]])

In [3]:
np.random.randn(5)

array([ 0.46354467,  0.56490935, -1.74021916,  1.22729641, -0.0703581 ])

In [4]:
np.random.ranf(5)

array([0.7773493 , 0.60203312, 0.5308145 , 0.17679267, 0.26849021])

In [5]:
np.random.randint(2,size=10)

array([1, 0, 1, 0, 0, 1, 0, 0, 0, 0])