In [1]:
import numpy as np
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
a.shape

(10,)

In [3]:
b=np.reshape(a,(5,2))
b

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
b.shape

(5, 2)

In [5]:
c=np.reshape(a,(5,2),order="F")
c

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [6]:
a.size

10

In [7]:
a.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [9]:
np.resize(a,(2,3))

array([[0, 1, 2],
       [3, 4, 0]])

In [10]:
np.resize(a,(5,2))

array([[0, 1],
       [2, 3],
       [4, 0],
       [1, 2],
       [3, 4]])