# **Slicing**

# 1-D Array

In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [2]:
a[2:5]

array([3, 4, 5])

In [3]:
a[:]

array([1, 2, 3, 4, 5, 6])

In [4]:
a[1::2]

array([2, 4, 6])

In [5]:
a[:3]

array([1, 2, 3])

# 2-D Array

In [6]:
b=np.array([[1,2],[3,4],[5,6]])
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
b[1:,1:]

array([[4],
       [6]])

In [8]:
b[:,:]

array([[1, 2],
       [3, 4],
       [5, 6]])