# **Zeros and Ones**

# **Zeros**

In [1]:
import numpy as np
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.zeros((2,3),dtype="int")

array([[0, 0, 0],
       [0, 0, 0]])

In [4]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.zeros(4,order="F")

array([0., 0., 0., 0.])

In [6]:
np.zeros((3,4),order="F")

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# **Ones :**

In [7]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.ones((2,3), dtype="int")

array([[1, 1, 1],
       [1, 1, 1]])

In [9]:
np.empty(6)          #random values

array([1.67233316e-316, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])